// -------------------------------------------------------
// Automatically generated with Kodeo's Reegenerator for NON-COMMERCIAL USE
// Generator: RgenTemplate (internal)
// Generation date: 2014-03-02 12:15
// Generated by: GATSU-DEV\Tedy.Pranolo
// -------------------------------------------------------
namespace T4ToRgen
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reegenerator", "2.0.5.0")]
    [Kodeo.Reegenerator.Generators.TemplateDisplayAttribute(DisplayName="CodeBehind", Description="CodeBehind", HideInDialog=false)]
    public partial class CodeBehind : CodeRendererEx
    {
        
        /// <summary>
        ///Renders the code as defined in the source script file.
        ///</summary>
        ///<returns></returns>
        public override Kodeo.Reegenerator.Generators.RenderResults Render()
        {
            this.Output.Write("//-------------------------------------------------------\r\n//Automatically genera" +
                    "ted with Kodeo\'s Reegenerator\r\n//Generator: CodeBehind\r\n//Generation date: ");
            this.Output.Write( System.DateTime.Now.ToString("yyyy-MM-dd hh:mm") );
            this.Output.Write("\r\n//Generated by: ");
            this.Output.Write( System.Security.Principal.WindowsIdentity.GetCurrent().Name );
            this.Output.Write("\r\n//-------------------------------------------------------\r\n");
 
	foreach(var ns in ImportedNamespaces ){
	
            this.Output.Write("\r\nusing ");
            this.Output.Write( ns );
            this.Output.Write(";");
	
	}

            this.Output.Write("\r\npublic class ");
            this.Output.Write( ClassName);
            this.Output.Write(" {\r\n");
            this.Output.Write( ClassMembers );
            this.Output.Write("\r\n}");
            this.Output.WriteLine();
            return new Kodeo.Reegenerator.Generators.RenderResults(this.Output.ToString());
        }
    }
}
