// -------------------------------------------------------
// Automatically generated with Kodeo's Reegenerator for NON-COMMERCIAL USE
// Generator: RgenTemplate (internal)
// Generation date: 2014-03-02 11:47
// Generated by: GATSU-DEV\Tedy.Pranolo
// -------------------------------------------------------
namespace T4ToRgen
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reegenerator", "2.0.5.0")]
    [Kodeo.Reegenerator.Generators.TemplateDisplayAttribute(DisplayName="T4ToRgenCS", Description="Converts a C# T4 Template to a Reegenator Template", HideInDialog=false)]
    [Kodeo.Reegenerator.Generators.DefaultExtensionAttribute(Extension=".txt")]
    public partial class T4ToRgenCS : CodeRendererEx
    {
    }
}
